module TD::Types
  # Describes an internal https://t.me or tg: link, which must be processed by the application in a special way.
  class InternalLinkType < Base
    %w[
      attachment_menu_bot
      authentication_code
      background
      bot_add_to_channel
      bot_start
      bot_start_in_group
      business_chat
      calls_page
      chat_affiliate_program
      chat_boost
      chat_folder_invite
      chat_invite
      chat_selection
      contacts_page
      direct_messages_chat
      game
      gift_auction
      gift_collection
      group_call
      instant_view
      invoice
      language_pack
      live_story
      main_web_app
      message
      message_draft
      my_profile_page
      new_channel_chat
      new_group_chat
      new_private_chat
      new_story
      oauth
      passport_data_request
      phone_number_confirmation
      premium_features_page
      premium_gift_code
      premium_gift_purchase
      proxy
      public_chat
      qr_code_authentication
      request_managed_bot
      restore_purchases
      saved_messages
      search
      settings
      star_purchase
      sticker_set
      story
      story_album
      text_composition_style
      theme
      unknown_deep_link
      upgraded_gift
      user_phone_number
      user_token
      video_chat
      web_app
    ].each do |type|
      autoload TD::Types.camelize(type), "tdlib/types/internal_link_type/#{type}"
    end
  end
end
