module TD::Types
  # A stake dice message.
  # The dice value is randomly generated by the server.
  #
  # @attr initial_state [TD::Types::DiceStickers, nil] The animated stickers with the initial dice animation; may be
  #   null if unknown.
  #   The update {TD::Types::Update::MessageContent} will be sent when the sticker became known.
  # @attr final_state [TD::Types::DiceStickers, nil] The animated stickers with the final dice animation; may be null
  #   if unknown.
  #   The update {TD::Types::Update::MessageContent} will be sent when the sticker became known.
  # @attr value [Integer] The dice value.
  #   If the value is 0, then the dice don't have final state yet.
  # @attr stake_gram_amount [Integer] The TON Gram amount that was staked; in the smallest units of the currency.
  # @attr prize_gram_amount [Integer] The TON Gram amount that was gained from the roll; in the smallest units of the
  #   currency; -1 if the dice don't have final state yet.
  class MessageContent::StakeDice < MessageContent
    attribute :initial_state, TD::Types::DiceStickers.optional.default(nil)
    attribute :final_state, TD::Types::DiceStickers.optional.default(nil)
    attribute :value, TD::Types::Coercible::Integer
    attribute :stake_gram_amount, TD::Types::Coercible::Integer
    attribute :prize_gram_amount, TD::Types::Coercible::Integer
  end
end
